 const CartActionTypes  = {
	TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
	ADD_ITEM : "ADD_ITEM",
	CEAR_ITEM_FROM_CART: "CEAR_ITEM_FROM_CART",
	DECREASE_QUANTITY: "DECREASE_QUANTITY"
}
export default CartActionTypes;